# Generated by Django 4.0.5 on 2022-06-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='department',
            field=models.CharField(default='departament', max_length=100),
        ),
    ]
